### ISSUE TITLE
\platforms\regina目录下idf.py build （5.1.3）编译报错：cmake failed with exit code 1

### ISSUE THREAD

**Issue by AINSITANcode** [Forairaaaaa/Regina#4]
编译环境：
平台：window11
esp-idf版本：5.1.3

报错日志：

`CMake Error at C:/Espressif/frameworks/esp-idf-v5.1.3/tools/cmake/project.cmake:349 (message):
  Directory specified in EXTRA_COMPONENT_DIRS doesn't exist:
  C:/Users/ASUS/Desktop/Regina-main/dependencies
Call Stack (most recent call first):
  C:/Espressif/frameworks/esp-idf-v5.1.3/tools/cmake/project.cmake:433 (__project_init)
  CMakeLists.txt:15 (project)
`
报错内容

`-- Configuring incomplete, errors occurred!
cmake failed with exit code 1, output of the command is in the C:\Users\ASUS\Desktop\Regina-main\platforms\regina\build\log\idf_py_stderr_output_8724 and C:\Users\ASUS\Desktop\Regina-main\platforms\regina\build\log\idf_py_stdout_output_8724`

**Comment by AINSITANcode** [comment]
桌面端编译也报错
`CMake Error at platforms/desktop/CMakeLists.txt:60 (add_subdirectory):
  add_subdirectory given source "dependencies/mooncake" which is not an
  existing directory.
Call Stack (most recent call first):
  CMakeLists.txt:9 (include)


CMake Error at platforms/desktop/CMakeLists.txt:63 (add_subdirectory):
  add_subdirectory given source "dependencies/smooth_ui_toolkit" which is not
  an existing directory.
Call Stack (most recent call first):
  CMakeLists.txt:9 (include)


-- Configuring incomplete, errors occurred!`

**Comment by Forairaaaaa** [comment]
没依赖

**Comment by AINSITANcode** [comment]
> 没依赖

怪了，下载依赖也报错
C:\Espressif\tools\idf-python\3.11.2\python.exe: can't open file 'C:\\Windows\\System32\\fetch_repos.py': [Errno 2] No such file or directory

**Comment by AINSITANcode** [comment]
> 没依赖
编译好了，但烧录时报错
`CMake Error at components/arduino_lite/CMakeLists.txt:292 (message):
  esp32-arduino requires CONFIG_FREERTOS_HZ=1000 (currently 100)


-- Configuring incomplete, errors occurred!`

日志
`-- git rev-parse returned 'fatal: not a git repository (or any of the parent directories): .git'
-- git rev-parse returned 'fatal: not a git repository (or any of the parent directories): .git'
-- Configuring incomplete, errors occurred!
`
